name: CI - SAST & DAST
on:
  push:
    branches: [ main ]

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- SAST: SonarQube Scan ---
      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=devsecops-demo
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # --- DAST: OWASP ZAP Scan ---
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network="host" \
          owasp/zap2docker-stable zap-baseline.py \
          -t http://localhost:8080 -r zap_report.html || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
